services:
  app:
    build: .
    environment:
      HOST: '0.0.0.0'
      PORT: '8157'
    volumes:
      - ./app:/app/app

  nginx:
    image: nginx:alpine
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    ports:
      - "8080:80"
    depends_on:
      - app